export const generatorDefinitions = [
  {
    id: 'circle',
    name: 'Circle',
    description: 'Generates a simple circle.',
    defaultParams: {
      radius: 0.5,
      numPoints: 50,
      x: 0,
      y: 0,
      r: 255,
      g: 255,
      b: 255,
      renderingStyle: 'normal',
      thickness: 1,
      blankingSize: 3
    },
    paramControls: [
      { id: 'radius', label: 'Radius', type: 'range', min: 0.01, max: 1.0, step: 0.01 },
      { id: 'numPoints', label: 'Number of Points', type: 'range', min: 3, max: 100, step: 1 },
      { id: 'renderingStyle', label: 'Beam Style', type: 'select', options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Dotted', value: 'dotted' },
          { label: 'Blanked', value: 'blanked' },
          { label: 'Dots', value: 'dots' }
      ]},
      { id: 'thickness', label: 'Thickness', type: 'range', min: 1, max: 10, step: 1, condition: (p) => p.renderingStyle === 'dotted' },
      { id: 'blankingSize', label: 'Blanking Size', type: 'range', min: 1, max: 20, step: 1, condition: (p) => p.renderingStyle === 'blanked' },
      { id: 'x', label: 'X Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'y', label: 'Y Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'r', label: 'Red', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'g', label: 'Green', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'b', label: 'Blue', type: 'range', min: 0, max: 255, step: 1 },
    ],
  },
  {
    id: 'square',
    name: 'Square',
    description: 'Generates a simple square.',
    defaultParams: {
      width: 1,
      height: 1,
      pointDensity: 12,
      x: 0,
      y: 0,
      r: 255,
      g: 255,
      b: 255,
      renderingStyle: 'normal',
      thickness: 1,
      blankingSize: 3
    },
    paramControls: [
      { id: 'width', label: 'Width', type: 'range', min: 0.01, max: 2.0, step: 0.01 },
      { id: 'height', label: 'Height', type: 'range', min: 0.01, max: 2.0, step: 0.01 },
      { id: 'pointDensity', label: 'Point Density', type: 'range', min: 1, max: 25, step: 1 },
      { id: 'renderingStyle', label: 'Beam Style', type: 'select', options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Dotted', value: 'dotted' },
          { label: 'Blanked', value: 'blanked' },
          { label: 'Dots', value: 'dots' }
      ]},
      { id: 'thickness', label: 'Thickness', type: 'range', min: 1, max: 10, step: 1, condition: (p) => p.renderingStyle === 'dotted' },
      { id: 'blankingSize', label: 'Blanking Size', type: 'range', min: 1, max: 20, step: 1, condition: (p) => p.renderingStyle === 'blanked' },
      { id: 'x', label: 'X Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'y', label: 'Y Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'r', label: 'Red', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'g', label: 'Green', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'b', label: 'Blue', type: 'range', min: 0, max: 255, step: 1 },
    ],
  },
  {
    id: 'triangle',
    name: 'Triangle',
    description: 'Generates a simple triangle.',
    defaultParams: {
      width: 1,
      height: 1,
      pointDensity: 12,
      x: 0,
      y: 0,
      r: 255,
      g: 255,
      b: 255,
      renderingStyle: 'normal',
      thickness: 1,
      blankingSize: 3
    },
    paramControls: [
      { id: 'width', label: 'Width', type: 'range', min: 0.01, max: 2.0, step: 0.01 },
      { id: 'height', label: 'Height', type: 'range', min: 0.01, max: 2.0, step: 0.01 },
      { id: 'pointDensity', label: 'Point Density', type: 'range', min: 1, max: 25, step: 1 },
      { id: 'renderingStyle', label: 'Beam Style', type: 'select', options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Dotted', value: 'dotted' },
          { label: 'Blanked', value: 'blanked' },
          { label: 'Dots', value: 'dots' }
      ]},
      { id: 'thickness', label: 'Thickness', type: 'range', min: 1, max: 10, step: 1, condition: (p) => p.renderingStyle === 'dotted' },
      { id: 'blankingSize', label: 'Blanking Size', type: 'range', min: 1, max: 20, step: 1, condition: (p) => p.renderingStyle === 'blanked' },
      { id: 'x', label: 'X Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'y', label: 'Y Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'r', label: 'Red', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'g', label: 'Green', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'b', label: 'Blue', type: 'range', min: 0, max: 255, step: 1 },
    ],
  },
  {
    id: 'line',
    name: 'Line',
    description: 'Generates a straight line.',
    defaultParams: {
      x1: -0.5,
      y1: 0,
      x2: 0.5,
      y2: 0,
      pointDensity: 50,
      r: 255,
      g: 255,
      b: 255,
      renderingStyle: 'normal',
      thickness: 1,
      blankingSize: 3
    },
    paramControls: [
      { id: 'x1', label: 'X1', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'y1', label: 'Y1', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'x2', label: 'X2', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'y2', label: 'Y2', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'pointDensity', label: 'Point Density', type: 'range', min: 2, max: 100, step: 1 },
      { id: 'renderingStyle', label: 'Beam Style', type: 'select', options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Dotted', value: 'dotted' },
          { label: 'Blanked', value: 'blanked' },
          { label: 'Dots', value: 'dots' }
      ]},
      { id: 'thickness', label: 'Thickness', type: 'range', min: 1, max: 10, step: 1, condition: (p) => p.renderingStyle === 'dotted' },
      { id: 'blankingSize', label: 'Blanking Size', type: 'range', min: 1, max: 20, step: 1, condition: (p) => p.renderingStyle === 'blanked' },
      { id: 'r', label: 'Red', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'g', label: 'Green', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'b', label: 'Blue', type: 'range', min: 0, max: 255, step: 1 },
    ],
  },
  {
    id: 'text',
    name: 'Text',
    description: 'Generates text.',
    defaultParams: {
      text: 'TrueLazer',
      x: 0,
      y: 0.3,
      fontSize: 72,
      numPoints: 100,
      fontUrl: 'src/fonts/Geometr415 Blk BT Black.ttf',
      r: 255,
      g: 255,
      b: 255,
      renderingStyle: 'normal',
      thickness: 1,
      blankingSize: 3
    },
    paramControls: [
      { id: 'text', label: 'Text Content', type: 'text' },
      { id: 'fontUrl', label: 'Fonts', type: 'text' },
      { id: 'x', label: 'X Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'y', label: 'Y Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'fontSize', label: 'Font Size', type: 'range', min: 10, max: 200, step: 1 },
      { id: 'numPoints', label: 'Target Points', type: 'range', min: 10, max: 300, step: 1 },
      { id: 'renderingStyle', label: 'Beam Style', type: 'select', options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Dotted', value: 'dotted' },
          { label: 'Blanked', value: 'blanked' },
          { label: 'Dots', value: 'dots' }
      ]},
      { id: 'thickness', label: 'Thickness', type: 'range', min: 1, max: 10, step: 1, condition: (p) => p.renderingStyle === 'dotted' },
      { id: 'blankingSize', label: 'Blanking Size', type: 'range', min: 1, max: 20, step: 1, condition: (p) => p.renderingStyle === 'blanked' },
      { id: 'r', label: 'Red', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'g', label: 'Green', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'b', label: 'Blue', type: 'range', min: 0, max: 255, step: 1 },
    ],
  },
  {
    id: 'star',
    name: 'Star',
    description: 'Generates a star shape.',
    defaultParams: {
      outerRadius: 0.5,
      innerRadius: 0.2,
      numSpikes: 5,
      pointDensity: 5,
      x: 0,
      y: 0,
      r: 255,
      g: 255,
      b: 255,
      renderingStyle: 'normal',
      thickness: 1,
      blankingSize: 3
    },
    paramControls: [
      { id: 'outerRadius', label: 'Outer Radius', type: 'range', min: 0.01, max: 1.0, step: 0.01 },
      { id: 'innerRadius', label: 'Inner Radius', type: 'range', min: 0.01, max: 1.0, step: 0.01 },
      { id: 'numSpikes', label: 'Number of Spikes', type: 'range', min: 3, max: 20, step: 1 },
      { id: 'pointDensity', label: 'Point Density', type: 'range', min: 1, max: 20, step: 1 },
      { id: 'renderingStyle', label: 'Beam Style', type: 'select', options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Dotted', value: 'dotted' },
          { label: 'Blanked', value: 'blanked' },
          { label: 'Dots', value: 'dots' }
      ]},
      { id: 'thickness', label: 'Thickness', type: 'range', min: 1, max: 10, step: 1, condition: (p) => p.renderingStyle === 'dotted' },
      { id: 'blankingSize', label: 'Blanking Size', type: 'range', min: 1, max: 20, step: 1, condition: (p) => p.renderingStyle === 'blanked' },
      { id: 'x', label: 'X Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'y', label: 'Y Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'r', label: 'Red', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'g', label: 'Green', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'b', label: 'Blue', type: 'range', min: 0, max: 255, step: 1 },
    ],
  },
  {
    id: 'ndi-source',
    name: 'NDI Source',
    description: 'Placeholder for NDI Video Input.',
    defaultParams: {
      sourceName: 'No Source',
      threshold: 128,
      edgeDetection: false,
      captureWidth: 480,
      captureHeight: 480,
      x: 0,
      y: 0,
      scale: 1,
      r: 255,
      g: 255,
      b: 255,
      renderingStyle: 'normal',
      thickness: 1,
      blankingSize: 3
    },
    paramControls: [
      { id: 'sourceName', label: 'Source Name', type: 'text' },
      { id: 'captureWidth', label: 'Width', type: 'range', min: 128, max: 1280, step: 1 },
      { id: 'captureHeight', label: 'Height', type: 'range', min: 128, max: 1280, step: 1 },
      { id: 'threshold', label: 'Threshold', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'edgeDetection', label: 'Edge Detection', type: 'checkbox' },
      { id: 'renderingStyle', label: 'Beam Style', type: 'select', options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Dotted', value: 'dotted' },
          { label: 'Blanked', value: 'blanked' },
          { label: 'Dots', value: 'dots' }
      ]},
      { id: 'thickness', label: 'Thickness', type: 'range', min: 1, max: 10, step: 1, condition: (p) => p.renderingStyle === 'dotted' },
      { id: 'blankingSize', label: 'Blanking Size', type: 'range', min: 1, max: 20, step: 1, condition: (p) => p.renderingStyle === 'blanked' },
      { id: 'scale', label: 'Scale', type: 'range', min: 0.1, max: 2.0, step: 0.1 },
      { id: 'x', label: 'X Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'y', label: 'Y Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'r', label: 'Red', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'g', label: 'Green', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'b', label: 'Blue', type: 'range', min: 0, max: 255, step: 1 },
    ],
  },
  {
    id: 'spout-receiver',
    name: 'Spout Receiver',
    description: 'Placeholder for Spout Video Input.',
    defaultParams: {
      sourceName: 'Spout Input',
      threshold: 128,
      edgeDetection: false,
      x: 0,
      y: 0,
      scale: 1,
      r: 255,
      g: 255,
      b: 255,
      renderingStyle: 'normal',
      thickness: 1,
      blankingSize: 3
    },
    paramControls: [
      { id: 'sourceName', label: 'Sender Name', type: 'text' },
      { id: 'threshold', label: 'Threshold', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'edgeDetection', label: 'Edge Detection', type: 'checkbox' },
      { id: 'renderingStyle', label: 'Beam Style', type: 'select', options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Dotted', value: 'dotted' },
          { label: 'Blanked', value: 'blanked' },
          { label: 'Dots', value: 'dots' }
      ]},
      { id: 'thickness', label: 'Thickness', type: 'range', min: 1, max: 10, step: 1, condition: (p) => p.renderingStyle === 'dotted' },
      { id: 'blankingSize', label: 'Blanking Size', type: 'range', min: 1, max: 20, step: 1, condition: (p) => p.renderingStyle === 'blanked' },
      { id: 'scale', label: 'Scale', type: 'range', min: 0.1, max: 2.0, step: 0.1 },
      { id: 'x', label: 'X Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'y', label: 'Y Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'r', label: 'Red', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'g', label: 'Green', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'b', label: 'Blue', type: 'range', min: 0, max: 255, step: 1 },
    ],
  },
  {
    id: 'sinewave',
    name: 'Sine Wave',
    description: 'Generates a customizable sine wave.',
    defaultParams: {
      amplitude: 0.5,
      frequency: 1,
      phase: 0,
      width: 2.0,
      numPoints: 50,
      x: 0,
      y: 0,
      r: 255,
      g: 255,
      b: 255,
      renderingStyle: 'normal',
      thickness: 1,
      blankingSize: 3
    },
    paramControls: [
      { id: 'amplitude', label: 'Amplitude', type: 'range', min: 0.0, max: 1.0, step: 0.01 },
      { id: 'frequency', label: 'Frequency', type: 'range', min: 0.1, max: 10.0, step: 0.1 },
      { id: 'phase', label: 'Phase', type: 'range', min: 0, max: Math.PI * 2, step: 0.01 },
      { id: 'width', label: 'Width', type: 'range', min: 0.1, max: 2.0, step: 0.01 },
      { id: 'numPoints', label: 'Number of Points', type: 'range', min: 10, max: 100, step: 1 },
      { id: 'renderingStyle', label: 'Beam Style', type: 'select', options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Dotted', value: 'dotted' },
          { label: 'Blanked', value: 'blanked' },
          { label: 'Dots', value: 'dots' }
      ]},
      { id: 'thickness', label: 'Thickness', type: 'range', min: 1, max: 10, step: 1, condition: (p) => p.renderingStyle === 'dotted' },
      { id: 'blankingSize', label: 'Blanking Size', type: 'range', min: 1, max: 20, step: 1, condition: (p) => p.renderingStyle === 'blanked' },
      { id: 'x', label: 'X Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'y', label: 'Y Position', type: 'range', min: -1.0, max: 1.0, step: 0.01 },
      { id: 'r', label: 'Red', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'g', label: 'Green', type: 'range', min: 0, max: 255, step: 1 },
      { id: 'b', label: 'Blue', type: 'range', min: 0, max: 255, step: 1 },
    ],
  },
];