import { describe, it, expect } from 'vitest';
import {
    MtcQuarterFrameDecoder,
    decodeMtcFullFrame,
    MidiClockTracker,
    encodeLtcBlock,
    encodeLtcFrames,
    decodeLtcBits,
    buildLtcBits,
    LtcBiphaseDecoder,
    parseArtnetTimecode,
    encodeArtnetTimecode,
    timecodeToSeconds,
    formatTimecode,
} from './timecodeSync';

// Helper: build MTC quarter-frame messages for a timecode.
// piece order: 0=frames units, 1=frames tens, 2=secs units, 3=secs tens,
//              4=mins units, 5=mins tens, 6=hours units, 7=hours tens
function mtcQuarters({ hours, minutes, seconds, frames }) {
    const vals = [
        frames % 10, Math.floor(frames / 10),
        seconds % 10, Math.floor(seconds / 10),
        minutes % 10, Math.floor(minutes / 10),
        hours % 10, Math.floor(hours / 10),
    ];
    return vals.map((v, piece) => [0xF1, (piece << 4) | v]);
}

describe('MTC (MIDI Timecode)', () => {
    it('reassembles a timecode from a full quarter-frame cycle', () => {
        const dec = new MtcQuarterFrameDecoder();
        let got = null;
        for (const msg of mtcQuarters({ hours: 12, minutes: 34, seconds: 56, frames: 29 })) {
            got = dec.push(msg);
        }
        expect(got).toEqual({ hours: 12, minutes: 34, seconds: 56, frames: 29 });
    });

    it('keeps decoding subsequent frames after a reset', () => {
        const dec = new MtcQuarterFrameDecoder();
        for (const msg of mtcQuarters({ hours: 1, minutes: 2, seconds: 3, frames: 4 })) dec.push(msg);
        let got = null;
        for (const msg of mtcQuarters({ hours: 9, minutes: 8, seconds: 7, frames: 6 })) got = dec.push(msg);
        expect(got).toEqual({ hours: 9, minutes: 8, seconds: 7, frames: 6 });
    });

    it('ignores incomplete cycles', () => {
        const dec = new MtcQuarterFrameDecoder();
        const partial = mtcQuarters({ hours: 5, minutes: 5, seconds: 5, frames: 5 }).slice(0, 4);
        for (const msg of partial) expect(dec.push(msg)).toBeNull();
    });

it('decodes a full-frame SysEx message', () => {
        // F0 7F <dev> 01 01 <hr> <mn> <sc> <fr> [user 8 bytes] F7
        const msg = [0xF0, 0x7F, 0x7F, 0x01, 0x01, 0x32, 0x56, 0x29, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xF7];
        // hr = 0x32 → &0x1F = 0x12 = hour 12 (BCD), rate = (0x32 >> 5) = 1 (25fps)
        const tc = decodeMtcFullFrame(msg);
        expect(tc).toEqual({ hours: 12, minutes: 56, seconds: 29, frames: 0, rate: 1 });
    });
});

describe('MIDI Clock', () => {
    it('converts 24 PPQN ticks to seconds at the given BPM', () => {
        const tracker = new MidiClockTracker(120); // 0.5s per beat, 24 ticks
        tracker.push([0xFA]);
        for (let i = 0; i < 24; i++) tracker.push([0xF8]);
        const snap = tracker.push(null);
        expect(snap).toEqual({ running: true, ticks: 24, seconds: 0.5 });
    });

    it('resets position on start and stops on stop', () => {
        const tracker = new MidiClockTracker(60); // 1s per beat
        tracker.push([0xFA]);
        for (let i = 0; i < 48; i++) tracker.push([0xF8]);
        expect(tracker.push(null).ticks).toBe(48);
        tracker.push([0xFC]);
        expect(tracker.push(null).running).toBe(false);
        tracker.push([0xFA]);
        expect(tracker.push(null).ticks).toBe(0);
    });

    it('honours Song Position Pointer overrides', () => {
        const tracker = new MidiClockTracker(120);
        tracker.push([0xFA, 0xF2, 0x02, 0x00]); // SPP = 2 sixteenths
        // 2 sixteenths = 2 * 6 ticks = 12 ticks → 0.25s @120bpm
        expect(tracker.push(null).ticks).toBe(12);
        expect(tracker.push(null).seconds).toBeCloseTo(0.25);
    });
});

describe('LTC biphase encode/decode', () => {
    it('builds the expected 80-bit frame with a valid sync word', () => {
        const bits = buildLtcBits({ hours: 12, minutes: 34, seconds: 56, frames: 29 });
        expect(bits).toHaveLength(80);
        expect(bits[0]).toBe(1);
        expect(bits[80 - 16]).toBe(0);
        expect(decodeLtcBits(bits)).toMatchObject({ hours: 12, minutes: 34, seconds: 56, frames: 29 });
    });

    it('round-trips a timecode generated by encodeLtcBlock', () => {
        const sampleRate = 48000;
        const fps = 30;
        const stream = encodeLtcBlock({ hours: 4, minutes: 5, seconds: 6, frames: 7 }, { fps, sampleRate });
        const dec = new LtcBiphaseDecoder({ fps, sampleRate });
        for (let off = 0; off < stream.length; off += 500) dec.push(stream.subarray(off, off + 500));
        expect(dec.framesDecoded).toBeGreaterThan(0);
        expect(dec.decode()).toMatchObject({ hours: 4, minutes: 5, seconds: 6, frames: 7 });
    });

    it('decodes consecutive frames continuously', () => {
        const sampleRate = 48000;
        const fps = 25;
        const stream = encodeLtcFrames([
            { hours: 10, minutes: 0, seconds: 0, frames: 0 },
            { hours: 10, minutes: 0, seconds: 0, frames: 1 },
            { hours: 10, minutes: 0, seconds: 0, frames: 2 },
        ], { fps, sampleRate });
        const dec = new LtcBiphaseDecoder({ fps, sampleRate });
        for (let off = 0; off < stream.length; off += 4000) {
            dec.push(stream.subarray(off, off + 4000));
        }
        expect(dec.framesDecoded).toBeGreaterThanOrEqual(2);
        expect(dec.decode()).toMatchObject({ hours: 10, minutes: 0 });
    });
});

describe('ArtNet Timecode', () => {
    it('parses an ArtTimeCode packet', () => {
        const pkt = encodeArtnetTimecode({ hours: 13, minutes: 45, seconds: 30, frames: 12, type: 3 });
        expect(parseArtnetTimecode(pkt)).toEqual({ hours: 13, minutes: 45, seconds: 30, frames: 12, type: 3 });
    });

    it('rejects packets without the ArtTimeCode opcode', () => {
        const pkt = encodeArtnetTimecode({ hours: 1, minutes: 0, seconds: 0, frames: 0 });
        pkt[9] = 0x20; // something else in place of 0x97
        expect(parseArtnetTimecode(pkt)).toBeNull();
    });

    it('ignores packets with the wrong ID', () => {
        const pkt = encodeArtnetTimecode({ hours: 1, minutes: 0, seconds: 0, frames: 0 });
        pkt[0] = 0x42; // 'B'
        expect(parseArtnetTimecode(pkt)).toBeNull();
    });

    it('ignores short packets', () => {
        expect(parseArtnetTimecode(new Uint8Array([1, 2, 3]))).toBeNull();
    });
});

describe('timecode helpers', () => {
    it('converts timecode to seconds with a frame rate', () => {
        expect(timecodeToSeconds({ hours: 0, minutes: 1, seconds: 30, frames: 0 }, 30)).toBe(90);
        expect(timecodeToSeconds({ hours: 0, minutes: 0, seconds: 0, frames: 15 }, 30)).toBeCloseTo(0.5);
    });

    it('formats into HH:MM:SS:FF', () => {
        expect(formatTimecode({ hours: 1, minutes: 2, seconds: 3, frames: 4 }, 30)).toBe('01:02:03:04');
    });
});